# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFrom', models.CharField(max_length=400)),
                ('userTo', models.CharField(max_length=400)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
